config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('messeneger.urls', 'config'), namespace='messeneger')),
    path('users/', include(('users.urls', 'config'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messeneger/urls.py
from django.urls import path
from . import views


app_name = 'messeneger' 
urlpatterns = [
    path('', views.home, name='home'),
    path('chat/<int:receiver_id>/', views.chat, name='chat'),
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
]

messeneger/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE, null=True)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE, null=True)
    messege = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender} to {self.receiver} at {self.timestamp}'

users/models.py
from django.db import models

# Create your models here.

messeneger/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['messege']
        widgets = {
            'messege': forms.Textarea(attrs={'rows': 2, 'placeholder': 'Type your message...'}),
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from messeneger.bulma_mixin import BulmaMixin


class SignUpForm(BulmaMixin, UserCreationForm):
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username is already taken.")
        return username


# class SignUpForm(BulmaMixin, UserCreationForm):
#     username = forms.CharField()

#     email = forms.CharField()

#     password1 = forms.PasswordInput()

#     password2 = forms.PasswordInput()

#     class Meta:
#         model = User
#         fields = ('username', 'email', 'password1', 'password2')


class SignInForm(BulmaMixin, AuthenticationForm):
    username = forms.CharField()
    password = forms.PasswordInput()

    class Meta:
        model = User
        fields = ['username', 'password']


class EditProfileForm(BulmaMixin, forms.ModelForm):
    first_name = forms.CharField(label='First name')
    last_name = forms.CharField(label='Last name')
    username = forms.CharField(label='Username')
    email = forms.CharField(label='Email address')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class ResetPasswordForm(BulmaMixin, PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(),
        label='Old password',
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(),
        label='New password',
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label='Repeat new password'
    )

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

messeneger/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Message
from django.contrib.auth.models import User
from django.db.models import Q
from . forms import MessageForm

@login_required(login_url='users/sign_in')
def home(request):
    users = User.objects.all()  
    current_user = request.user
    search = request.GET.get('search', '')


    if search:
        search_results = users.filter(
            Q(username__icontains=search) 
        )
        if not search_results.exists():
            search_results = users
        users = search_results 

    return render(request, 'home.html', {
        'users': users,
        'current_user':current_user,
    })


@login_required
def chat(request, receiver_id):

    receiver = User.objects.get(id=receiver_id)

    sender = request.user
    users = User.objects.all()  



    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.receiver = receiver
            message.save()
            return redirect('messeneger:chat', receiver_id=receiver_id)  
    else:
        form = MessageForm()

    # Get messages between sender and receiver
    messages = Message.objects.filter(
        (Q(sender=sender) & Q(receiver=receiver)) | 
        (Q(sender=receiver) & Q(receiver=sender))
    ).order_by('timestamp')


    context = {
        'receiver': receiver,
        'messages': messages,
        'form': form,
        'users': users,
        'current_user': request.user, 
    }
    return render(request, 'chat.html', context)

users/views.py
from django.contrib.auth import login, logout, update_session_auth_hash, authenticate
from django.shortcuts import render, redirect
from .forms import ResetPasswordForm, SignUpForm, SignInForm, EditProfileForm, PasswordChangeForm
from django.contrib import messages


def sign_up(request):
    form = SignUpForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('messeneger:home')
    return render(request, 'sign_up.html', {
        'form': form
    })


def sign_in(request):
    form = SignInForm(data=request.POST or None)
    if request.method == 'POST' and form.is_valid():
        user = form.get_user()
        login(request, user)
        return redirect('messeneger:home')
    return render(request, 'sign_in.html', {
        'form': form
    })


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')


def edit_profile(request):
    form = EditProfileForm(request.POST or None, instance=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Ваш профиль успешно обновлен.')
        return redirect('messeneger:home')
    return render(request, 'edit_profile.html', {'form': form})


def reset_password(request):
    form = ResetPasswordForm(request.user, request.POST)
    if request.method == 'POST':
        if form.is_valid():
            messages.success(request, 'Пароль успешно изменен.')
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('users:sign_in')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки в форме.')
    else:
        form = ResetPasswordForm(request.user)
    return render(request, 'reset_password.html', {'form': form})

messeneger/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Messenger</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
</head>
<body>
    {% if user.is_authenticated %}
        {% block content %}
        {% endblock %}    
    {% else %} 
        {% block auth %}
        {% endblock %}
    {% endif %} 
</body>
</html>

messeneger/templates/chat.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{% comment %} <h1>Chat with {{ receiver.username }}</h1>
    
    <div class="messages">
      {% if messages %}
        {% for message in messages %}
            <div class="message">
                <strong>{{ message.sender.username }}:</strong>
                <p>{{ message.messege }}</p>
                <small>{{ message.timestamp }}</small>
            </div>
        {% endfor %}
      {% endif %}
    </div>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form> {% endcomment %}

<!-- <nav class="navbar navbar-default no-margin">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav">
          <li class="active">
             <button class="navbar-toggle collapse in" data-toggle="collapse" id="menu-toggle-2"> <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
             </button>
          </li>
       </ul>
    </div>

 </nav> -->

 <div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        
       <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
          <li class="search">
             <!-- <a href="#"><input type="text" name="search" id="search"></a> -->
             <form action="{% url 'messeneger:home' %}" method="get">
                <input id="search" type="search" placeholder="Search user ..." name="search">
              </form>
          </li>
            {% for user in users %}
                {% if current_user != user%}
                    <li class="indent ">
                        <a href="{% url 'messeneger:chat' receiver_id=user.id %}" class="{% if user.username == receiver.username %}it-is{% endif %}">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-cloud-download fa-stack-1x "></i>
                            </span>{{ user.username }}
                        </a>
                    </li>
                  {% else %}
                    <li class="indent">
                       <a href="{% url 'messeneger:chat' receiver_id=user.id %}">
                          <span class="fa-stack fa-lg pull-left">
                             <i class="fa fa-cloud-download fa-stack-1x "></i>
                          </span>Saved
                       </a>
                 </li>
                {% endif %}
            {% endfor %}
            <!-- and user.name in user_chat  -->
       </ul>
    </div>
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
       <div class="container-fluid xyz">
          <div class="row">
            <div class="col-lg-12">
               <div class="messages">
                  {% if messages %}
                    {% for message in messages %}
                        <div class="message {% if message.sender == user %}my-message{% else %}other-message{% endif %}">
                            <!-- <strong>{{ message.sender.username }}:</strong> -->
                            <p>{{ message.messege }}</p>
                            <small>{{ message.timestamp }}</small>
                        </div>
                    {% endfor %}
                  {% endif %}
                </div>
               <form method="post" class="form">
                  {% csrf_token %}
                  <input class="sms" type="text" name="messege" id="{{ form.messege.id_for_label }}" accept="text" placeholder="Write anything">
                  <button class="send" type="submit"><img src="{% static 'images/send.png' %}" alt=""></button>
              </form>
            </div>
          </div>
       </div>
    </div>
 </div>

<script>
    $("#menu-toggle").click(function(e) {
   e.preventDefault();
   $("#wrapper").toggleClass("toggled");
});
$("#menu-toggle-2").click(function(e) {
   e.preventDefault();
   $("#wrapper").toggleClass("toggled-2");
   $('#menu ul').hide();
});

function initMenu() {
   $('#menu ul').hide();
   $('#menu ul').children('.current').parent().show();
   //$('#menu ul:first').show();
   $('#menu li a').click(
      function() {
         var checkElement = $(this).next();
         if ((checkElement.is('ul')) && (checkElement.is(':visible'))) {
            return false;
         }
         if ((checkElement.is('ul')) && (!checkElement.is(':visible'))) {
            $('#menu ul:visible').slideUp('normal');
            checkElement.slideDown('normal');
            return false;
         }
      }
   );
}
$(document).ready(function() {
   initMenu();
});
</script> 

{% endblock %}

messeneger/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}

 <div id="wrapper">
    <div id="sidebar-wrapper">
        
       <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
          <li class="search">
             <form action="{% url 'messeneger:home' %}" method="get">
                <input id="search" type="search" placeholder="Search user ..." name="search">
              </form>
          </li>
            <!-- {% for user in users %}
                <li class="indent">
                    <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-cloud-download fa-stack-1x "></i></span>{{ user.username }} </a>
                 </li>
            {% endfor %} -->
            {% for user in users %}
                {% if current_user != user %}
                    <li class="indent">
                        <a href="{% url 'messeneger:chat' receiver_id=user.id %}">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-cloud-download fa-stack-1x "></i>
                            </span>{{ user.username }}
                        </a>
                    </li>
                {% else %}
                  <li class="indent">
                     <a href="{% url 'messeneger:chat' receiver_id=user.id %}">
                        <span class="fa-stack fa-lg pull-left">
                           <i class="fa fa-cloud-download fa-stack-1x "></i>
                        </span>Saved
                     </a>
               </li>
                {% endif %}
            {% endfor %}
       </ul>
    </div>
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
       <div class="container-fluid xyz">
          <div class="row">
             <div class="col-lg-12">
                <h1>Simple Admin Sidebar With Bootstrap by</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident laudantium nobis cum dignissimos ex inventore, velit blanditiis. Quod laborum soluta quidem culpa officia eligendi, quam, recusandae iste aliquid amet odit! </p>
             </div>
          </div>
       </div>
    </div>
 </div>

<div class="container">
    <div class="columns">
        <ul>
            
        </ul>
    </div>
</div>
<script>
    $("#menu-toggle").click(function(e) {
   e.preventDefault();
   $("#wrapper").toggleClass("toggled");
});
$("#menu-toggle-2").click(function(e) {
   e.preventDefault();
   $("#wrapper").toggleClass("toggled-2");
   $('#menu ul').hide();
});

function initMenu() {
   $('#menu ul').hide();
   $('#menu ul').children('.current').parent().show();
   //$('#menu ul:first').show();
   $('#menu li a').click(
      function() {
         var checkElement = $(this).next();
         if ((checkElement.is('ul')) && (checkElement.is(':visible'))) {
            return false;
         }
         if ((checkElement.is('ul')) && (!checkElement.is(':visible'))) {
            $('#menu ul:visible').slideUp('normal');
            checkElement.slideDown('normal');
            return false;
         }
      }
   );
}
$(document).ready(function() {
   initMenu();
});
</script>

{% endblock %}

messeneger/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
hello world
</body>
</html>

users/templates/edit_profile.html
{% extends 'base.html' %}

{% block auth %}
   <div class="columns is-centered" style="margin-top: 8%">
       <div class="column is-4">
           <div class="box" style="background: rgba(2,86,94,0.78)">
               <form class="form  has-text-centered" method="post">
                   {% csrf_token %}
                        <h1 class="has-text-centered is-size-2 has-text-white has-text-bold"><b>Edit profile</b></h1>
                        <div class="field">
                            <hr class="has-background-grey-lighter">
                            <input class="input is-rounded" type="text" name="firs_name" id="{{ form.first_name.id_for_label }}" placeholder="First name">
                        </div><hr class="has-background-grey-lighter">
                        <div class="field">
                            <input class="input is-rounded" type="text" name="last_name" id="{{ form.last_name.id_for_label }}" placeholder="Last name">
                        </div>
                   <hr class="has-background-grey-lighter">
                        <div class="field ">
                            <input class="input is-rounded" type="text" name="username" id="{{ form.username.id_for_label }}" placeholder="User name">
                        </div>
                   <hr class="has-background-grey-lighter">
                        <div class="field ">
                            <input class="input is-rounded" type="text" name="email" id="{{ form.email.id_for_label }}" placeholder="Email">
                        </div>
                   <hr class="has-background-grey-lighter">
                        <button type="submit" class="button is-primary  is-fullwidth is-light is-outlined">Submit</button>
               </form>
           </div>
       </div>
   </div>
    <style>
        .input {
            background-color: rgba(251, 255, 254, 0.81);
        }
    </style>
{% endblock %}


{#{% extends 'base_layout.html' %}#}
{##}
{#{% block auth %}#}
{#    <div class="columns is-centered">#}
{#        <div class="column is-4">#}
{#            <div class="box has-background-info-light">#}
{#                <form class="form  has-text-centered" method="post" enctype="multipart/form-data">#}
{#                    <h1 class="title is-size-2 has-text-centered">Edit profile</h1>#}
{#                    {% csrf_token %}#}
{#                    {% for field in form %}#}
{#                        <div class="field">#}
{#                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>#}
{#                            {{ field }}#}
{#                        </div>#}
{#                    {% endfor %}#}
{#                    <button type="submit" class="button is-primary is-fullwidth">#}
{#                        Submit#}
{#                    </button>#}
{#                </form>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}

users/templates/reset_password.html
{% extends 'base.html' %}

{% block auth %}
   <div class="columns is-centered" style="margin-top: 8%">
       <div class="column is-4">
           <div class="box" style="background: rgba(2,86,94,0.78)">
               <form class="form  has-text-centered" method="post">
                   {% csrf_token %}
                        <h1 class="has-text-centered is-size-2 has-text-white has-text-bold"><b>Reset password</b></h1>
                        <div class="field">
                            <hr class="has-background-grey-lighter">
                            <input class="input is-rounded" type="text" name="old_password" id="{{ form.old_password.id_for_label }}" placeholder="Old password">
                        </div><hr class="has-background-grey-lighter">
                        <div class="field">
                            <input class="input is-rounded" type="text" name="new_password1" id="{{ form.new_password1.id_for_label }}" placeholder="New password">
                        </div>
                   <hr class="has-background-grey-lighter">
                        <div class="field ">
                            <input class="input is-rounded" type="text" name="new_password2" id="{{ form.new_password2.id_for_label }}" placeholder="Repeat password">
                        </div>
                   <hr class="has-background-grey-lighter">
                        <button type="submit" class="button is-primary  is-fullwidth is-light is-outlined">Submit</button>
{#                   <hr class="has-background-grey-lighter">#}

               </form>
           </div>
       </div>
   </div>
    <style>
        .input {
            background-color: rgba(251, 255, 254, 0.81);
        }
    </style>
{% endblock %}




{#{% extends 'base_layout.html' %}#}
{##}
{#{% block auth %}#}
{#    <div class="columns is-centered">#}
{#        <div class="column is-4">#}
{#            <div class="box has-background-info-light">#}
{#                <form class="form  has-text-centered" method="post">#}
{#                    <h1 class="title is-size-2 has-text-centered">Reset password</h1>#}
{#                    {% csrf_token %}#}
{#                    {% for field in form %}#}
{#                        <div class="field">#}
{#                            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>#}
{#                            {{ field }}#}
{#                        </div>#}
{#                    {% endfor %}#}
{#                    <button type="submit" class="button is-primary is-fullwidth">#}
{#                        Submit#}
{#                    </button>#}
{#                </form>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}

users/templates/sign_in.html
    {% extends 'base.html' %}

    {% block auth %}
        <div class="columns is-centered" style="margin-top: 6%">
            <div class="column is-4">
                <div class="box" style="background: rgba(2,86,94,0.78)">
                    <form class="form  has-text-centered" method="post">
                        {% csrf_token %}
                        <h1 class="has-text-centered has-text-white is-size-3 has-text-bold"><b>Log in</b></h1>
                        <div class="field add_category_input">
                            <hr>
                            <input class="input input_expense is-rounded" type="text" name="username" id="{{ form.username.id_for_label }}" placeholder="User name">
                        </div><hr>
                        <div class="field add_category_input">
                            <input class="input input_expense is-rounded" type="password" name="password" id="{{ form.password.id_for_label }}" placeholder="Password">
                        </div>
                        <hr>
                        <button type="submit" class="button is-primary is-fullwidth is-light is-outlined">Submit</button>
{#                        <h1 class="title is-size-2 has-text-centered">Sign in</h1>#}
{#                        {% csrf_token %}#}
{#                        {% for field in form %}#}
{#                            <div class="field">#}
{#                                <label class="label" for="{{ field.id_for_label }}">{{ field.label }}</label>#}
{#                                {{ field }}#}
{#                            </div>#}
{#                        {% endfor %}#}
{#                        <button type="submit" class="button is-primary is-fullwidth">#}
{#                            Submit#}
{#                        </button>#}
                        <p class="content mt-3 has-text-white">
                            If you don't have an account
                            <a href="{% url 'users:sign_up' %}" class="has-text-primary"> Sign up here</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
        <style>
        .input {
            background-color: rgba(251, 255, 254, 0.81);
        }
        </style>
    {% endblock %}



users/templates/sign_up.html
{% extends 'base.html' %}

{% block auth %}
<br>
   <div class="columns is-centered" >
       <div class="column is-4">
           <div class="box" style="background: rgba(2,86,94,0.78)">
               <form class="form  has-text-centered" method="post">
                   {% csrf_token %}
                        <h1 class="has-text-centered is-size-2 has-text-white has-text-bold"><b>Sign up</b></h1>
                        <div class="field">
                            <hr class="has-background-grey-lighter">
                            <input class="input is-rounded" type="text" name="username" id="{{ form.username.id_for_label }}" placeholder="User name">
                        </div><hr class="has-background-grey-lighter">
                        <div class="field">
                            <input class="input is-rounded" type="text" name="email" id="{{ form.email.id_for_label }}" placeholder="Email">
                        </div>
                   <hr class="has-background-grey-lighter">
                        <div class="field ">
                            <input class="input is-rounded" type="password" name="password1" id="{{ form.password1.id_for_label }}" placeholder="Password">
                        </div>
                   <hr class="has-background-grey-lighter">
                        <div class="field">
                            <input class="input is-rounded" type="password" name="password2" id="{{ form.password2.id_for_label }}" placeholder="Repeat your password">
                        </div>
                        <hr class="has-background-grey-lighter">
                        <button type="submit" class="button is-primary  is-fullwidth is-light is-outlined">Submit</button>
                   <hr class="has-background-grey-lighter">
               </form>
               <div class="password-generator">
                    <input type="text" id="generated-password" class="input is-rounded has-text-centered" readonly  placeholder="Click the button below to generate password"><br>
                   <button class="button is-primary has-background-primary-soft is-fullwidth is-light is-outlined mt-3" onclick="generatePassword()">Generate Password</button>
                </div>
               <hr>
               <p class="has-text-white has-text-centered">If you have an account
               <a href="{% url 'users:sign_in' %}" class="has-text-primary">
                       Login please
               </a>
               </p>

           </div>
       </div>
   </div>
    <style>
        .input {
            background-color: rgba(251, 255, 254, 0.81);
        }
    </style>
    <script>
    // JavaScript функция для генерации пароля
    function generatePassword() {
        // Строка, содержащая все возможные символы для пароля
        var chars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ,.:;?/}{][!@#$%&*()_";
        var passwordLength = 12; // Длина пароля
        var password = ""; // Инициализация пустой строки для пароля

        // Генерация пароля
        for (var i = 0; i < passwordLength; i++) {
            var randomIndex = Math.floor(Math.random() * chars.length);
            password += chars[randomIndex]; // Добавляем случайный символ к паролю
        }

        // Вставляем сгенерированный пароль в текстовое поле
        document.getElementById('generated-password').value = password;
    }
</script>
{% endblock %}

